services:
  neo4j:
    image: neo4j:5.26.0-community-bullseye
    container_name: neo4j
    environment:
      - NEO4J_initial_dbms_default__database
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data/neo4j:/data
