services:
  neo4j:
    image: neo4j:5.26.0-community-bullseye
    container_name: neo4j
    environment:
      - NEO4J_AUTH_FILE
      - NEO4J_initial_dbms_default__database
      - NEO4J_server_memory_heap_max__size
      - NEO4J_server_memory_pagecache_size
    ports:
      - "7474:7474"
      - "7687:7687"
    secrets:
      - neo4j_pass
    volumes:
      - ./data/neo4j:/data

secrets:
  neo4j_pass:
    file: ./secrets/neo4j.txt
