services:
  api:
    image: ghcr.io/aartoni/sixdegreesofapi:main
    container_name: api
    environment:
      - RUST_LOG=${API_LOG_LEVEL}
      - PORT=${API_PORT}
    ports:
      - "${API_PORT}:${API_PORT}"
  db:
    image: neo4j:5.26.0-community-bullseye
    container_name: db
    environment:
      - NEO4J_AUTH_FILE
      - NEO4J_initial_dbms_default__database
      - NEO4J_server_memory_heap_initial__size
      - NEO4J_server_memory_heap_max__size
    ports:
      - "7474:7474"
      - "7687:7687"
    secrets:
      - neo4j_pass
    volumes:
      - ./data/neo4j:/data
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080

secrets:
  neo4j_pass:
    file: ./secrets/neo4j.txt
